{
 "title": "GEN24 Solarflow Dynamische Strompreise",
 "description": " ab Firmware 1.35.4-1",
 "time": { "from": "now/d", "to": "now/d" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Solarflow",
   "type": "lehmannch-flow-panel",
   "gridPos": { "h": 12, "w": 13, "x": 0, "y": 0 },
   "targets": [
    {
     "global_query_id": "my-query-1",
     "parser": "backend",
     "root_selector": "$sum(Body.Data.\"0\".channels.(PV_POWERACTIVE_MEAN_01_F32 + PV_POWERACTIVE_MEAN_02_F32))",
     "source": "url",
     "type": "json",
     "url_options": { "data": "", "method": "GET" }
    },
    {
     "global_query_id": "my-query-1",
     "parser": "backend",
     "root_selector": "$.Body.Data.\"16252928\".channels.SMARTMETER_POWERACTIVE_MEAN_SUM_F64",
     "source": "url",
     "type": "json",
     "url_options": { "data": "", "method": "GET" }
    },
    {
     "global_query_id": "my-query-1",
     "parser": "backend",
     "root_selector": "$.Body.Data.\"0\".channels.BAT_POWERACTIVE_MEAN_F32",
     "source": "url",
     "type": "json",
     "url_options": { "data": "", "method": "GET" }
    }
   ]
  },
  {
   "title": "Überblick",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 11, "x": 13, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "global_query_id": "my-query-1",
     "parser": "backend",
     "root_selector": "$.Body.Data.\"16252928\".channels.SMARTMETER_POWERACTIVE_MEAN_SUM_F64",
     "source": "url",
     "type": "json",
     "url_options": { "data": "", "method": "GET" }
    },
    {
     "global_query_id": "my-query-1",
     "parser": "backend",
     "root_selector": "$sum(Body.Data.\"0\".channels.(PV_POWERACTIVE_MEAN_01_F32 + PV_POWERACTIVE_MEAN_02_F32))",
     "source": "url",
     "type": "json",
     "url_options": { "data": "", "method": "GET" }
    },
    {
     "global_query_id": "my-query-1",
     "parser": "backend",
     "root_selector": "$.Body.Data.\"0\".channels.BAT_POWERACTIVE_MEAN_F32",
     "source": "url",
     "type": "json",
     "url_options": { "data": "", "method": "GET" }
    },
    {
     "global_query_id": "my-query-1",
     "parser": "backend",
     "root_selector": "$.Body.Data.\"16580608\".channels.BAT_VALUE_STATE_OF_CHARGE_RELATIVE_U16",
     "source": "url",
     "type": "json",
     "url_options": {
      "body_content_type": "text/plain",
      "body_type": "raw",
      "data": "",
      "headers": [
       { "key": "header-key", "value": "header-value" }
      ],
      "method": "GET"
     }
    }
   ]
  },
  {
   "title": "Stromkosten heute",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 13, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "WITH verbrauchview AS (\n    SELECT\n        Zeitpunkt,\n        Netzverbrauch,\n        AC_TO_DC,\n        LEAD(Netzverbrauch) OVER (ORDER BY Zeitpunkt) - Netzverbrauch AS \"Netzverbrauch_pro_stunde\",\n        LEAD(AC_TO_DC) OVER (ORDER BY Zeitpunkt) - AC_TO_DC AS \"AC_TO_DC_pro_stunde\"\n    FROM pv_daten\n    WHERE\n        Zeitpunkt >= datetime($__from / 1000 - 3600, 'unixepoch') AND\n        Zeitpunkt <= datetime($__to / 1000 + 3600, 'unixepoch')\n),\nstundenweise_verbrauch AS (\n    SELECT\n        strftime('%Y-%m-%d %H:00:00', Zeitpunkt) AS \"Stunde\",\n        SUM(Netzverbrauch_pro_stunde)  AS \"Netzverbrauch_pro_stunde\",\n        SUM(AC_TO_DC_pro_stunde) AS \"AC_TO_DC_pro_stunde\"\n    FROM verbrauchview\n    WHERE\n        Zeitpunkt >= datetime($__from / 1000 , 'unixepoch') AND\n        Zeitpunkt <= datetime($__to / 1000 , 'unixepoch')\n    GROUP BY strftime('%Y-%m-%d %H:00:00', Zeitpunkt)\n),\ntagesweise_kosten AS (\n    SELECT\n        strftime('%Y-%m-%d', sv.Stunde) AS \"Tag\",\n        SUM(sv.Netzverbrauch_pro_stunde) AS \"Tagesverbrauch\",\n        SUM(sv.AC_TO_DC_pro_stunde) AS \"Tages_AC_TO_DC\",  -- Summe von AC_TO_DC pro Tag\n        SUM(sv.Netzverbrauch_pro_stunde * sp.Bruttopreis) AS \"Tagesstromkosten\",\n        MIN(sp.Bruttopreis) AS \"Minimaler_Strompreis\",\n        MAX(sp.Bruttopreis) AS \"Maximaler_Strompreis\",\n        AVG(sp.Bruttopreis) AS \"Durchschnittspreis\",\n        SUM(sv.Netzverbrauch_pro_stunde * sp.Bruttopreis) / SUM(sv.Netzverbrauch_pro_stunde) AS \"Mein_Durchschnittspreis_Verbrauch\"\n    FROM stundenweise_verbrauch sv\n    JOIN Strompreise sp ON sv.Stunde = strftime('%Y-%m-%d %H:00:00', sp.Zeitpunkt)\n    GROUP BY strftime('%Y-%m-%d', sv.Stunde)\n)\nSELECT\n    --Tag,\n    -- ROUND(Tagesverbrauch / 1000.0, 2) AS \"Tagesverbrauch_kWh\",  -- Umrechnung in kWh mit 2 Nachkommastellen\n    -- ROUND(Tages_AC_TO_DC / 1000.0, 2) AS \"Tages_AC_TO_DC\", \n    -- Tagesverbrauch,\n    -- Tages_AC_TO_DC, \n     ROUND(Tagesstromkosten / 1000.0, 2) \n    -- Mein_Durchschnittspreis_Verbrauch,  \n    -- Minimaler_Strompreis,\n    -- Maximaler_Strompreis,\n    -- Durchschnittspreis       \nFROM tagesweise_kosten\nORDER BY Tag;",
     "rawQueryText": "WITH verbrauchview AS (\n    SELECT\n        Zeitpunkt,\n        Netzverbrauch,\n        AC_TO_DC,\n        LEAD(Netzverbrauch) OVER (ORDER BY Zeitpunkt) - Netzverbrauch AS \"Netzverbrauch_pro_stunde\",\n        LEAD(AC_TO_DC) OVER (ORDER BY Zeitpunkt) - AC_TO_DC AS \"AC_TO_DC_pro_stunde\"\n    FROM pv_daten\n    WHERE\n        Zeitpunkt >= datetime($__from / 1000 - 3600, 'unixepoch') AND\n        Zeitpunkt <= datetime($__to / 1000 + 3600, 'unixepoch')\n),\nstundenweise_verbrauch AS (\n    SELECT\n        strftime('%Y-%m-%d %H:00:00', Zeitpunkt) AS \"Stunde\",\n        SUM(Netzverbrauch_pro_stunde)  AS \"Netzverbrauch_pro_stunde\",\n        SUM(AC_TO_DC_pro_stunde) AS \"AC_TO_DC_pro_stunde\"\n    FROM verbrauchview\n    WHERE\n        Zeitpunkt >= datetime($__from / 1000 , 'unixepoch') AND\n        Zeitpunkt <= datetime($__to / 1000 , 'unixepoch')\n    GROUP BY strftime('%Y-%m-%d %H:00:00', Zeitpunkt)\n),\ntagesweise_kosten AS (\n    SELECT\n        strftime('%Y-%m-%d', sv.Stunde) AS \"Tag\",\n        SUM(sv.Netzverbrauch_pro_stunde) AS \"Tagesverbrauch\",\n        SUM(sv.AC_TO_DC_pro_stunde) AS \"Tages_AC_TO_DC\",  -- Summe von AC_TO_DC pro Tag\n        SUM(sv.Netzverbrauch_pro_stunde * sp.Bruttopreis) AS \"Tagesstromkosten\",\n        MIN(sp.Bruttopreis) AS \"Minimaler_Strompreis\",\n        MAX(sp.Bruttopreis) AS \"Maximaler_Strompreis\",\n        AVG(sp.Bruttopreis) AS \"Durchschnittspreis\",\n        SUM(sv.Netzverbrauch_pro_stunde * sp.Bruttopreis) / SUM(sv.Netzverbrauch_pro_stunde) AS \"Mein_Durchschnittspreis_Verbrauch\"\n    FROM stundenweise_verbrauch sv\n    JOIN Strompreise sp ON sv.Stunde = strftime('%Y-%m-%d %H:00:00', sp.Zeitpunkt)\n    GROUP BY strftime('%Y-%m-%d', sv.Stunde)\n)\nSELECT\n    --Tag,\n    -- ROUND(Tagesverbrauch / 1000.0, 2) AS \"Tagesverbrauch_kWh\",  -- Umrechnung in kWh mit 2 Nachkommastellen\n    -- ROUND(Tages_AC_TO_DC / 1000.0, 2) AS \"Tages_AC_TO_DC\", \n    -- Tagesverbrauch,\n    -- Tages_AC_TO_DC, \n     ROUND(Tagesstromkosten / 1000.0, 2) \n    -- Mein_Durchschnittspreis_Verbrauch,  \n    -- Minimaler_Strompreis,\n    -- Maximaler_Strompreis,\n    -- Durchschnittspreis       \nFROM tagesweise_kosten\nORDER BY Tag;",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "ø Preis/kWh",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 17, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "WITH verbrauchview AS (\n    SELECT\n        Zeitpunkt,\n        Netzverbrauch,\n        AC_TO_DC,\n        LEAD(Netzverbrauch) OVER (ORDER BY Zeitpunkt) - Netzverbrauch AS \"Netzverbrauch_pro_stunde\",\n        LEAD(AC_TO_DC) OVER (ORDER BY Zeitpunkt) - AC_TO_DC AS \"AC_TO_DC_pro_stunde\"\n    FROM pv_daten\n    WHERE\n        Zeitpunkt >= datetime($__from / 1000 - 3600, 'unixepoch') AND\n        Zeitpunkt <= datetime($__to / 1000 + 3600, 'unixepoch')\n),\nstundenweise_verbrauch AS (\n    SELECT\n        strftime('%Y-%m-%d %H:00:00', Zeitpunkt) AS \"Stunde\",\n        SUM(Netzverbrauch_pro_stunde)  AS \"Netzverbrauch_pro_stunde\",\n        SUM(AC_TO_DC_pro_stunde) AS \"AC_TO_DC_pro_stunde\"\n    FROM verbrauchview\n    WHERE\n        Zeitpunkt >= datetime($__from / 1000 , 'unixepoch') AND\n        Zeitpunkt <= datetime($__to / 1000 , 'unixepoch')\n    GROUP BY strftime('%Y-%m-%d %H:00:00', Zeitpunkt)\n),\ntagesweise_kosten AS (\n    SELECT\n        strftime('%Y-%m-%d', sv.Stunde) AS \"Tag\",\n        SUM(sv.Netzverbrauch_pro_stunde) AS \"Tagesverbrauch\",\n        SUM(sv.AC_TO_DC_pro_stunde) AS \"Tages_AC_TO_DC\",  -- Summe von AC_TO_DC pro Tag\n        SUM(sv.Netzverbrauch_pro_stunde * sp.Bruttopreis) AS \"Tagesstromkosten\",\n        MIN(sp.Bruttopreis) AS \"Minimaler_Strompreis\",\n        MAX(sp.Bruttopreis) AS \"Maximaler_Strompreis\",\n        AVG(sp.Bruttopreis) AS \"Durchschnittspreis\",\n        SUM(sv.Netzverbrauch_pro_stunde * sp.Bruttopreis) / SUM(sv.Netzverbrauch_pro_stunde) AS \"Mein_Durchschnittspreis_Verbrauch\"\n    FROM stundenweise_verbrauch sv\n    JOIN Strompreise sp ON sv.Stunde = strftime('%Y-%m-%d %H:00:00', sp.Zeitpunkt)\n    GROUP BY strftime('%Y-%m-%d', sv.Stunde)\n)\nSELECT\n    --Tag,\n    -- ROUND(Tagesverbrauch / 1000.0, 2) AS \"Tagesverbrauch_kWh\",  -- Umrechnung in kWh mit 2 Nachkommastellen\n    -- ROUND(Tages_AC_TO_DC / 1000.0, 2) AS \"Tages_AC_TO_DC\", \n    -- Tagesverbrauch,\n    -- Tages_AC_TO_DC, \n    -- Tagesstromkosten,\n    Mein_Durchschnittspreis_Verbrauch\n   -- Minimaler_Strompreis,\n   -- Maximaler_Strompreis,\n   -- Durchschnittspreis       \nFROM tagesweise_kosten\nORDER BY Tag;",
     "rawQueryText": "WITH verbrauchview AS (\n    SELECT\n        Zeitpunkt,\n        Netzverbrauch,\n        AC_TO_DC,\n        LEAD(Netzverbrauch) OVER (ORDER BY Zeitpunkt) - Netzverbrauch AS \"Netzverbrauch_pro_stunde\",\n        LEAD(AC_TO_DC) OVER (ORDER BY Zeitpunkt) - AC_TO_DC AS \"AC_TO_DC_pro_stunde\"\n    FROM pv_daten\n    WHERE\n        Zeitpunkt >= datetime($__from / 1000 - 3600, 'unixepoch') AND\n        Zeitpunkt <= datetime($__to / 1000 + 3600, 'unixepoch')\n),\nstundenweise_verbrauch AS (\n    SELECT\n        strftime('%Y-%m-%d %H:00:00', Zeitpunkt) AS \"Stunde\",\n        SUM(Netzverbrauch_pro_stunde)  AS \"Netzverbrauch_pro_stunde\",\n        SUM(AC_TO_DC_pro_stunde) AS \"AC_TO_DC_pro_stunde\"\n    FROM verbrauchview\n    WHERE\n        Zeitpunkt >= datetime($__from / 1000 , 'unixepoch') AND\n        Zeitpunkt <= datetime($__to / 1000 , 'unixepoch')\n    GROUP BY strftime('%Y-%m-%d %H:00:00', Zeitpunkt)\n),\ntagesweise_kosten AS (\n    SELECT\n        strftime('%Y-%m-%d', sv.Stunde) AS \"Tag\",\n        SUM(sv.Netzverbrauch_pro_stunde) AS \"Tagesverbrauch\",\n        SUM(sv.AC_TO_DC_pro_stunde) AS \"Tages_AC_TO_DC\",  -- Summe von AC_TO_DC pro Tag\n        SUM(sv.Netzverbrauch_pro_stunde * sp.Bruttopreis) AS \"Tagesstromkosten\",\n        MIN(sp.Bruttopreis) AS \"Minimaler_Strompreis\",\n        MAX(sp.Bruttopreis) AS \"Maximaler_Strompreis\",\n        AVG(sp.Bruttopreis) AS \"Durchschnittspreis\",\n        SUM(sv.Netzverbrauch_pro_stunde * sp.Bruttopreis) / SUM(sv.Netzverbrauch_pro_stunde) AS \"Mein_Durchschnittspreis_Verbrauch\"\n    FROM stundenweise_verbrauch sv\n    JOIN Strompreise sp ON sv.Stunde = strftime('%Y-%m-%d %H:00:00', sp.Zeitpunkt)\n    GROUP BY strftime('%Y-%m-%d', sv.Stunde)\n)\nSELECT\n    --Tag,\n    -- ROUND(Tagesverbrauch / 1000.0, 2) AS \"Tagesverbrauch_kWh\",  -- Umrechnung in kWh mit 2 Nachkommastellen\n    -- ROUND(Tages_AC_TO_DC / 1000.0, 2) AS \"Tages_AC_TO_DC\", \n    -- Tagesverbrauch,\n    -- Tages_AC_TO_DC, \n    -- Tagesstromkosten,\n    Mein_Durchschnittspreis_Verbrauch\n   -- Minimaler_Strompreis,\n   -- Maximaler_Strompreis,\n   -- Durchschnittspreis       \nFROM tagesweise_kosten\nORDER BY Tag;",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "aktueller Preis/kWh",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "WITH Stundenpreise AS (\n  SELECT\n    Zeitpunkt,\n    Bruttopreis\n  FROM Strompreise\n  WHERE\n    Zeitpunkt >= datetime($__from / 1000 - 3600, 'unixepoch') AND\n    Zeitpunkt <= datetime($__to / 1000 + 3600 , 'unixepoch')\n)\n\n\nSELECT \n  Bruttopreis\nFROM Stundenpreise\nWHERE Zeitpunkt = datetime(strftime('%Y-%m-%d %H:00:00', 'now', 'localtime'));\n\n\n  ",
     "rawQueryText": "WITH Stundenpreise AS (\n  SELECT\n    Zeitpunkt,\n    Bruttopreis\n  FROM Strompreise\n  WHERE\n    Zeitpunkt >= datetime($__from / 1000 - 3600, 'unixepoch') AND\n    Zeitpunkt <= datetime($__to / 1000 + 3600 , 'unixepoch')\n)\n\n\nSELECT \n  Bruttopreis\nFROM Stundenpreise\nWHERE Zeitpunkt = datetime(strftime('%Y-%m-%d %H:00:00', 'now', 'localtime'));\n\n\n  ",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Strompreise",
   "type": "stat",
   "gridPos": { "h": 3, "w": 11, "x": 13, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "\n\nWITH timemove AS (\n  SELECT\n    Zeitpunkt,\n    Bruttopreis AS \"Bruttopreis\"\n  FROM strompreise\n  WHERE\n    Zeitpunkt >= datetime($__from / 1000 - 3600, 'unixepoch') AND\n    Zeitpunkt <= datetime($__to / 1000 + 3600, 'unixepoch')\n)\nSELECT\n  strftime('%Y-%m-%d', Zeitpunkt) AS \"Tag\",\n  MAX(Bruttopreis) AS \"Maximaler_Strompreis\",\n  MIN(Bruttopreis) AS \"Minimaler_Strompreis\",\n  AVG(Bruttopreis) AS \"Durchschnittspreis\"\nFROM timemove\nWHERE\n  Zeitpunkt >= datetime($__from / 1000, 'unixepoch') AND\n  Zeitpunkt <= datetime($__to / 1000, 'unixepoch')\nGROUP BY strftime('%Y-%m-%d', Zeitpunkt)\nORDER BY Tag;",
     "rawQueryText": "\n\nWITH timemove AS (\n  SELECT\n    Zeitpunkt,\n    Bruttopreis AS \"Bruttopreis\"\n  FROM strompreise\n  WHERE\n    Zeitpunkt >= datetime($__from / 1000 - 3600, 'unixepoch') AND\n    Zeitpunkt <= datetime($__to / 1000 + 3600, 'unixepoch')\n)\nSELECT\n  strftime('%Y-%m-%d', Zeitpunkt) AS \"Tag\",\n  MAX(Bruttopreis) AS \"Maximaler_Strompreis\",\n  MIN(Bruttopreis) AS \"Minimaler_Strompreis\",\n  AVG(Bruttopreis) AS \"Durchschnittspreis\"\nFROM timemove\nWHERE\n  Zeitpunkt >= datetime($__from / 1000, 'unixepoch') AND\n  Zeitpunkt <= datetime($__to / 1000, 'unixepoch')\nGROUP BY strftime('%Y-%m-%d', Zeitpunkt)\nORDER BY Tag;",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Heute",
   "type": "stat",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "WITH verbrauchview AS (\nSELECT\n  Zeitpunkt,\n  LEAD(AC_Produktion) OVER (ORDER BY Zeitpunkt) - AC_Produktion AS \"AC_Produktion\",\n  LEAD(DC_Produktion) OVER (ORDER BY Zeitpunkt) - DC_Produktion AS \"DC_Produktion\",\n  LEAD(Netzverbrauch) OVER (ORDER BY Zeitpunkt) - Netzverbrauch AS \"Netzverbrauch\",\n  LEAD(Einspeisung) OVER (ORDER BY Zeitpunkt) - Einspeisung AS \"Einspeisung\",\n  LEAD(Batterie_IN) OVER (ORDER BY Zeitpunkt) - Batterie_IN AS \"Batterie_IN\",\n  LEAD(Batterie_OUT) OVER (ORDER BY Zeitpunkt) - Batterie_OUT AS \"Batterie_OUT\",\n  LEAD(AC_to_DC) OVER (ORDER BY Zeitpunkt) - AC_to_DC AS \"AC_to_DC\"\nFROM pv_daten\nWHERE\n  Zeitpunkt >= datetime($__from / 1000 - 3600, 'unixepoch') AND\n  Zeitpunkt <= datetime($__to / 1000 + 3600, 'unixepoch')\n)\nSELECT\n \n  sum (Netzverbrauch) + sum(AC_Produktion) - sum(Einspeisung) AS \"Gesamtverbrauch\", \n  sum(Netzverbrauch) AS \"Netzverbrauch\",\n  sum(AC_to_DC) AS \"Batterie aus Netz geladen\",\n  sum(AC_Produktion) AS \"AC Produktion\",\n  sum(DC_Produktion) AS \"DC Produktion\",\n  sum(Einspeisung) AS \"Einspeisung\",\n  sum(Batterie_In) AS \"In Batterie\",\n  sum(Batterie_Out) AS \"Aus Batterie\"\nFROM verbrauchview\nWHERE\n        Zeitpunkt >= datetime($__from / 1000, 'unixepoch') AND\n        Zeitpunkt <= datetime($__to / 1000, 'unixepoch')\nORDER BY strftime('%Y-%m-%d %H:00:00', Zeitpunkt);",
     "rawQueryText": "WITH verbrauchview AS (\nSELECT\n  Zeitpunkt,\n  LEAD(AC_Produktion) OVER (ORDER BY Zeitpunkt) - AC_Produktion AS \"AC_Produktion\",\n  LEAD(DC_Produktion) OVER (ORDER BY Zeitpunkt) - DC_Produktion AS \"DC_Produktion\",\n  LEAD(Netzverbrauch) OVER (ORDER BY Zeitpunkt) - Netzverbrauch AS \"Netzverbrauch\",\n  LEAD(Einspeisung) OVER (ORDER BY Zeitpunkt) - Einspeisung AS \"Einspeisung\",\n  LEAD(Batterie_IN) OVER (ORDER BY Zeitpunkt) - Batterie_IN AS \"Batterie_IN\",\n  LEAD(Batterie_OUT) OVER (ORDER BY Zeitpunkt) - Batterie_OUT AS \"Batterie_OUT\",\n  LEAD(AC_to_DC) OVER (ORDER BY Zeitpunkt) - AC_to_DC AS \"AC_to_DC\"\nFROM pv_daten\nWHERE\n  Zeitpunkt >= datetime($__from / 1000 - 3600, 'unixepoch') AND\n  Zeitpunkt <= datetime($__to / 1000 + 3600, 'unixepoch')\n)\nSELECT\n \n  sum (Netzverbrauch) + sum(AC_Produktion) - sum(Einspeisung) AS \"Gesamtverbrauch\", \n  sum(Netzverbrauch) AS \"Netzverbrauch\",\n  sum(AC_to_DC) AS \"Batterie aus Netz geladen\",\n  sum(AC_Produktion) AS \"AC Produktion\",\n  sum(DC_Produktion) AS \"DC Produktion\",\n  sum(Einspeisung) AS \"Einspeisung\",\n  sum(Batterie_In) AS \"In Batterie\",\n  sum(Batterie_Out) AS \"Aus Batterie\"\nFROM verbrauchview\nWHERE\n        Zeitpunkt >= datetime($__from / 1000, 'unixepoch') AND\n        Zeitpunkt <= datetime($__to / 1000, 'unixepoch')\nORDER BY strftime('%Y-%m-%d %H:00:00', Zeitpunkt);",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 21 },
   "options": {
    "content": "<div style=\"display: flex; justify-content: space-between; font-family: Arial, sans-serif;\">\n  <div style=\"width: 48%;\">\n    <h4 style=\"color: #1F78B4;\">Links zu anderen Dashboards</h4>\n    <hr style=\"border: 1px solid #1F78B4; margin-top: 5px; margin-bottom: 10px;\"> <!-- Farbige Linie -->\n    <ul style=\"font-size: 15px; color: #000000; list-style-type: none; padding: 0;\">\n      <li><a href=\"/d/dash01?kiosk&theme=light\" target=\"_self\" style=\"color: #000000; text-decoration: none;\">Energiestatistiken</a></li>\n      <li><a href=\"/d/dash02?kiosk&theme=light\" target=\"_self\" style=\"color: #000000; text-decoration: none;\">Tagesauswertung</a></li>\n      <li><a href=\"/d/dash03?kiosk&theme=light\" target=\"_self\" style=\"color: #000000; text-decoration: none;\">Strompreise</a></li>\n    </ul>\n  </div>\n  <div style=\"width: 48%;\">\n    <h4 style=\"color: #FFFFFF;\">Spalte 2</h4> <!-- Überschrift in Gelb -->\n    <hr style=\"border: 1px solid #1F78B4; margin-top: 5px; margin-bottom: 10px;\"> <!-- Farbige Linie -->\n    <ul style=\"font-size: 15px; color: #000000; list-style-type: none; padding: 0;\">\n      <li><a href=\"/d/dash04?kiosk&theme=light\" target=\"_self\" style=\"color: #000000; text-decoration: none;\">Preisstatistiken</a></li>\n      <li><a href=\"/d/dash05?kiosk&theme=light\" target=\"_self\" style=\"color: #000000; text-decoration: none;\">Strompreisentwicklung</a></li>\n      <li><a href=\"/d/dash06?kiosk&theme=light\" target=\"_self\" style=\"color: #000000; text-decoration: none;\">Smartphone Solar</a></li>\n    </ul>\n  </div>\n</div>"
   }
  }
 ]
}