{
 "title": "Preisstatistiken",
 "time": { "from": "now/d", "to": "now/d" },
 "panels": [
  {
   "title": "Heute",
   "type": "table",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "queryText": "WITH verbrauchview AS (\n    SELECT\n        Zeitpunkt,\n        LEAD(Netzverbrauch) OVER (ORDER BY Zeitpunkt) - Netzverbrauch AS Netzverbrauch_pro_stunde,\n        LEAD(AC_TO_DC) OVER (ORDER BY Zeitpunkt) - AC_TO_DC AS AC_TO_DC_pro_stunde,\n        LEAD(AC_Produktion) OVER (ORDER BY Zeitpunkt) - AC_Produktion AS AC_Produktion_pro_stunde,\n        LEAD(DC_Produktion) OVER (ORDER BY Zeitpunkt) - DC_Produktion AS DC_Produktion_pro_stunde,\n        LEAD(Einspeisung) OVER (ORDER BY Zeitpunkt) - Einspeisung AS Einspeisung_pro_stunde,\n        LEAD(Batterie_IN) OVER (ORDER BY Zeitpunkt) - Batterie_IN AS Batterie_IN_pro_stunde,\n        LEAD(Batterie_OUT) OVER (ORDER BY Zeitpunkt) - Batterie_OUT AS Batterie_OUT_pro_stunde\n    FROM pv_daten\n    WHERE\n        Zeitpunkt >= datetime($__from / 1000 - 3600, 'unixepoch') AND\n        Zeitpunkt <= datetime($__to / 1000 + 3600, 'unixepoch')\n),\nstundenweise_verbrauch AS (\n    SELECT\n        strftime('%Y-%m-%d %H:00:00', Zeitpunkt) AS Stunde,\n        SUM(Netzverbrauch_pro_stunde) AS Netzverbrauch_pro_stunde,\n        SUM(AC_TO_DC_pro_stunde) AS AC_TO_DC_pro_stunde\n    FROM verbrauchview\n    WHERE\t                                                         -- Und hier grenzt man das Ergebnis wieder ein, damit man nur den ausgewählten Zeitraum bekommt\n  Zeitpunkt >= datetime($__from / 1000, 'unixepoch') AND\n  Zeitpunkt <= datetime($__to / 1000, 'unixepoch')\n    GROUP BY strftime('%Y-%m-%d %H:00:00', Zeitpunkt)\n),\ntagesweise_kosten AS (\n    SELECT\n        strftime('%d-%m-%Y', sv.Stunde) AS Tag,  -- Datumsformat: Tag-Monat-Jahr\n        SUM(sv.Netzverbrauch_pro_stunde) AS Tagesverbrauch,\n        SUM(sv.Netzverbrauch_pro_stunde * sp.Bruttopreis) AS Tagesstromkosten,\n        MIN(sp.Bruttopreis) AS Minimaler_Strompreis,\n        MAX(sp.Bruttopreis) AS Maximaler_Strompreis,\n        AVG(sp.Bruttopreis) AS Durchschnittspreis,\n        SUM(sv.Netzverbrauch_pro_stunde * sp.Bruttopreis) / SUM(sv.Netzverbrauch_pro_stunde) AS Mein_Durchschnittspreis_Verbrauch\n    FROM stundenweise_verbrauch sv\n    \n    JOIN Strompreise sp ON sv.Stunde = strftime('%Y-%m-%d %H:00:00', sp.Zeitpunkt)\n    GROUP BY strftime('%d-%m-%Y', sv.Stunde)  -- Gruppierung nach Tag-Monat-Jahr\n)\nSELECT\n    \n    Tagesverbrauch,\n    ROUND(Tagesstromkosten / 1000.0,2 ) as Tagesstromkosten, \n    Mein_Durchschnittspreis_Verbrauch,\n    Durchschnittspreis,\n    Minimaler_Strompreis,\n    Maximaler_Strompreis\n\nFROM tagesweise_kosten\n\nORDER BY strftime('%Y-%m-%d', Tag) ASC;  -- Sortierung aufsteigend (ältester Eintrag zuerst)",
     "rawQueryText": "WITH verbrauchview AS (\n    SELECT\n        Zeitpunkt,\n        LEAD(Netzverbrauch) OVER (ORDER BY Zeitpunkt) - Netzverbrauch AS Netzverbrauch_pro_stunde,\n        LEAD(AC_TO_DC) OVER (ORDER BY Zeitpunkt) - AC_TO_DC AS AC_TO_DC_pro_stunde,\n        LEAD(AC_Produktion) OVER (ORDER BY Zeitpunkt) - AC_Produktion AS AC_Produktion_pro_stunde,\n        LEAD(DC_Produktion) OVER (ORDER BY Zeitpunkt) - DC_Produktion AS DC_Produktion_pro_stunde,\n        LEAD(Einspeisung) OVER (ORDER BY Zeitpunkt) - Einspeisung AS Einspeisung_pro_stunde,\n        LEAD(Batterie_IN) OVER (ORDER BY Zeitpunkt) - Batterie_IN AS Batterie_IN_pro_stunde,\n        LEAD(Batterie_OUT) OVER (ORDER BY Zeitpunkt) - Batterie_OUT AS Batterie_OUT_pro_stunde\n    FROM pv_daten\n    WHERE\n        Zeitpunkt >= datetime($__from / 1000 - 3600, 'unixepoch') AND\n        Zeitpunkt <= datetime($__to / 1000 + 3600, 'unixepoch')\n),\nstundenweise_verbrauch AS (\n    SELECT\n        strftime('%Y-%m-%d %H:00:00', Zeitpunkt) AS Stunde,\n        SUM(Netzverbrauch_pro_stunde) AS Netzverbrauch_pro_stunde,\n        SUM(AC_TO_DC_pro_stunde) AS AC_TO_DC_pro_stunde\n    FROM verbrauchview\n    WHERE\t                                                         -- Und hier grenzt man das Ergebnis wieder ein, damit man nur den ausgewählten Zeitraum bekommt\n  Zeitpunkt >= datetime($__from / 1000, 'unixepoch') AND\n  Zeitpunkt <= datetime($__to / 1000, 'unixepoch')\n    GROUP BY strftime('%Y-%m-%d %H:00:00', Zeitpunkt)\n),\ntagesweise_kosten AS (\n    SELECT\n        strftime('%d-%m-%Y', sv.Stunde) AS Tag,  -- Datumsformat: Tag-Monat-Jahr\n        SUM(sv.Netzverbrauch_pro_stunde) AS Tagesverbrauch,\n        SUM(sv.Netzverbrauch_pro_stunde * sp.Bruttopreis) AS Tagesstromkosten,\n        MIN(sp.Bruttopreis) AS Minimaler_Strompreis,\n        MAX(sp.Bruttopreis) AS Maximaler_Strompreis,\n        AVG(sp.Bruttopreis) AS Durchschnittspreis,\n        SUM(sv.Netzverbrauch_pro_stunde * sp.Bruttopreis) / SUM(sv.Netzverbrauch_pro_stunde) AS Mein_Durchschnittspreis_Verbrauch\n    FROM stundenweise_verbrauch sv\n    \n    JOIN Strompreise sp ON sv.Stunde = strftime('%Y-%m-%d %H:00:00', sp.Zeitpunkt)\n    GROUP BY strftime('%d-%m-%Y', sv.Stunde)  -- Gruppierung nach Tag-Monat-Jahr\n)\nSELECT\n    \n    Tagesverbrauch,\n    ROUND(Tagesstromkosten / 1000.0,2 ) as Tagesstromkosten, \n    Mein_Durchschnittspreis_Verbrauch,\n    Durchschnittspreis,\n    Minimaler_Strompreis,\n    Maximaler_Strompreis\n\nFROM tagesweise_kosten\n\nORDER BY strftime('%Y-%m-%d', Tag) ASC;  -- Sortierung aufsteigend (ältester Eintrag zuerst)",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Tage",
   "type": "table",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 4 },
   "targets": [
    {
     "queryText": "WITH verbrauchview AS (\n    SELECT\n        Zeitpunkt,\n        LEAD(Netzverbrauch) OVER (ORDER BY Zeitpunkt) - Netzverbrauch AS Netzverbrauch_pro_stunde,\n        LEAD(AC_TO_DC) OVER (ORDER BY Zeitpunkt) - AC_TO_DC AS AC_TO_DC_pro_stunde,\n        LEAD(AC_Produktion) OVER (ORDER BY Zeitpunkt) - AC_Produktion AS AC_Produktion_pro_stunde,\n        LEAD(DC_Produktion) OVER (ORDER BY Zeitpunkt) - DC_Produktion AS DC_Produktion_pro_stunde,\n        LEAD(Einspeisung) OVER (ORDER BY Zeitpunkt) - Einspeisung AS Einspeisung_pro_stunde,\n        LEAD(Batterie_IN) OVER (ORDER BY Zeitpunkt) - Batterie_IN AS Batterie_IN_pro_stunde,\n        LEAD(Batterie_OUT) OVER (ORDER BY Zeitpunkt) - Batterie_OUT AS Batterie_OUT_pro_stunde\n    FROM pv_daten\n    WHERE\n        Zeitpunkt >= datetime($__from / 1000 - 3600, 'unixepoch') AND\n        Zeitpunkt <= datetime($__to / 1000 + 3600, 'unixepoch')\n),\nstundenweise_verbrauch AS (\n    SELECT\n        strftime('%Y-%m-%d %H:00:00', Zeitpunkt) AS Stunde,\n        SUM(Netzverbrauch_pro_stunde) AS Netzverbrauch_pro_stunde,\n        SUM(AC_TO_DC_pro_stunde) AS AC_TO_DC_pro_stunde\n    FROM verbrauchview\n    WHERE\t                                                         -- Und hier grenzt man das Ergebnis wieder ein, damit man nur den ausgewählten Zeitraum bekommt\n  Zeitpunkt >= datetime($__from / 1000, 'unixepoch') AND\n  Zeitpunkt <= datetime($__to / 1000, 'unixepoch')\n    GROUP BY strftime('%Y-%m-%d %H:00:00', Zeitpunkt)\n),\ntagesweise_kosten AS (\n    SELECT\n        strftime('%d.%m.%Y', sv.Stunde) AS Tag,  -- Datumsformat: Tag.Monat.Jahr\n        SUM(sv.Netzverbrauch_pro_stunde) AS Tagesverbrauch,\n        SUM(sv.Netzverbrauch_pro_stunde * sp.Bruttopreis) AS Tagesstromkosten,\n        MIN(sp.Bruttopreis) AS Minimaler_Strompreis,\n        MAX(sp.Bruttopreis) AS Maximaler_Strompreis,\n        AVG(sp.Bruttopreis) AS Durchschnittspreis,\n        SUM(sv.Netzverbrauch_pro_stunde * sp.Bruttopreis) / SUM(sv.Netzverbrauch_pro_stunde) AS Mein_Durchschnittspreis_Verbrauch\n    FROM stundenweise_verbrauch sv\n    JOIN Strompreise sp ON sv.Stunde = strftime('%Y-%m-%d %H:00:00', sp.Zeitpunkt)\n    GROUP BY strftime('%Y-%m-%d', sv.Stunde)  -- Gruppierung nach Jahr-Monat-Tag\n)\nSELECT\n    Tag,\n    Tagesverbrauch,\n    ROUND(Tagesstromkosten / 1000.0, 2) AS Tagesstromkosten,\n    Mein_Durchschnittspreis_Verbrauch,\n    Durchschnittspreis,\n    Minimaler_Strompreis,\n    Maximaler_Strompreis\nFROM tagesweise_kosten\nORDER BY date(substr(Tag, 7, 4) || '-' || substr(Tag, 4, 2) || '-' || substr(Tag, 1, 2)) DESC;",
     "rawQueryText": "WITH verbrauchview AS (\n    SELECT\n        Zeitpunkt,\n        LEAD(Netzverbrauch) OVER (ORDER BY Zeitpunkt) - Netzverbrauch AS Netzverbrauch_pro_stunde,\n        LEAD(AC_TO_DC) OVER (ORDER BY Zeitpunkt) - AC_TO_DC AS AC_TO_DC_pro_stunde,\n        LEAD(AC_Produktion) OVER (ORDER BY Zeitpunkt) - AC_Produktion AS AC_Produktion_pro_stunde,\n        LEAD(DC_Produktion) OVER (ORDER BY Zeitpunkt) - DC_Produktion AS DC_Produktion_pro_stunde,\n        LEAD(Einspeisung) OVER (ORDER BY Zeitpunkt) - Einspeisung AS Einspeisung_pro_stunde,\n        LEAD(Batterie_IN) OVER (ORDER BY Zeitpunkt) - Batterie_IN AS Batterie_IN_pro_stunde,\n        LEAD(Batterie_OUT) OVER (ORDER BY Zeitpunkt) - Batterie_OUT AS Batterie_OUT_pro_stunde\n    FROM pv_daten\n    WHERE\n        Zeitpunkt >= datetime($__from / 1000 - 3600, 'unixepoch') AND\n        Zeitpunkt <= datetime($__to / 1000 + 3600, 'unixepoch')\n),\nstundenweise_verbrauch AS (\n    SELECT\n        strftime('%Y-%m-%d %H:00:00', Zeitpunkt) AS Stunde,\n        SUM(Netzverbrauch_pro_stunde) AS Netzverbrauch_pro_stunde,\n        SUM(AC_TO_DC_pro_stunde) AS AC_TO_DC_pro_stunde\n    FROM verbrauchview\n    WHERE\t                                                         -- Und hier grenzt man das Ergebnis wieder ein, damit man nur den ausgewählten Zeitraum bekommt\n  Zeitpunkt >= datetime($__from / 1000, 'unixepoch') AND\n  Zeitpunkt <= datetime($__to / 1000, 'unixepoch')\n    GROUP BY strftime('%Y-%m-%d %H:00:00', Zeitpunkt)\n),\ntagesweise_kosten AS (\n    SELECT\n        strftime('%d.%m.%Y', sv.Stunde) AS Tag,  -- Datumsformat: Tag.Monat.Jahr\n        SUM(sv.Netzverbrauch_pro_stunde) AS Tagesverbrauch,\n        SUM(sv.Netzverbrauch_pro_stunde * sp.Bruttopreis) AS Tagesstromkosten,\n        MIN(sp.Bruttopreis) AS Minimaler_Strompreis,\n        MAX(sp.Bruttopreis) AS Maximaler_Strompreis,\n        AVG(sp.Bruttopreis) AS Durchschnittspreis,\n        SUM(sv.Netzverbrauch_pro_stunde * sp.Bruttopreis) / SUM(sv.Netzverbrauch_pro_stunde) AS Mein_Durchschnittspreis_Verbrauch\n    FROM stundenweise_verbrauch sv\n    JOIN Strompreise sp ON sv.Stunde = strftime('%Y-%m-%d %H:00:00', sp.Zeitpunkt)\n    GROUP BY strftime('%Y-%m-%d', sv.Stunde)  -- Gruppierung nach Jahr-Monat-Tag\n)\nSELECT\n    Tag,\n    Tagesverbrauch,\n    ROUND(Tagesstromkosten / 1000.0, 2) AS Tagesstromkosten,\n    Mein_Durchschnittspreis_Verbrauch,\n    Durchschnittspreis,\n    Minimaler_Strompreis,\n    Maximaler_Strompreis\nFROM tagesweise_kosten\nORDER BY date(substr(Tag, 7, 4) || '-' || substr(Tag, 4, 2) || '-' || substr(Tag, 1, 2)) DESC;",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Monate",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 15 },
   "targets": [
    {
     "queryText": "WITH verbrauchview AS (\n    SELECT\n        Zeitpunkt,\n        LEAD(Netzverbrauch) OVER (ORDER BY Zeitpunkt) - Netzverbrauch AS Netzverbrauch_pro_stunde,\n        LEAD(AC_TO_DC) OVER (ORDER BY Zeitpunkt) - AC_TO_DC AS AC_TO_DC_pro_stunde,\n        LEAD(AC_Produktion) OVER (ORDER BY Zeitpunkt) - AC_Produktion AS AC_Produktion_pro_stunde,\n        LEAD(DC_Produktion) OVER (ORDER BY Zeitpunkt) - DC_Produktion AS DC_Produktion_pro_stunde,\n        LEAD(Einspeisung) OVER (ORDER BY Zeitpunkt) - Einspeisung AS Einspeisung_pro_stunde,\n        LEAD(Batterie_IN) OVER (ORDER BY Zeitpunkt) - Batterie_IN AS Batterie_IN_pro_stunde,\n        LEAD(Batterie_OUT) OVER (ORDER BY Zeitpunkt) - Batterie_OUT AS Batterie_OUT_pro_stunde\n    FROM pv_daten\n    WHERE\n        Zeitpunkt >= datetime($__from / 1000 - 3600, 'unixepoch') AND\n        Zeitpunkt <= datetime($__to / 1000 + 3600, 'unixepoch')\n),\nstundenweise_verbrauch AS (\n    SELECT\n        strftime('%Y-%m-%d %H:00:00', Zeitpunkt) AS Stunde,\n        SUM(Netzverbrauch_pro_stunde) AS Netzverbrauch_pro_stunde,\n        SUM(AC_TO_DC_pro_stunde) AS AC_TO_DC_pro_stunde\n    FROM verbrauchview\n    WHERE\n        Zeitpunkt >= datetime($__from / 1000 , 'unixepoch') AND\n        Zeitpunkt <= datetime($__to / 1000 , 'unixepoch')\n    GROUP BY strftime('%Y-%m-%d %H:00:00', Zeitpunkt)\n),\ntagesweise_kosten AS (\n    SELECT\n        strftime('%Y-%m-%d', sv.Stunde) AS Tag,\n        SUM(sv.Netzverbrauch_pro_stunde) AS Tagesverbrauch,\n        SUM(sv.Netzverbrauch_pro_stunde * sp.Bruttopreis) AS Tagesstromkosten,\n        MIN(sp.Bruttopreis) AS Minimaler_Strompreis,\n        MAX(sp.Bruttopreis) AS Maximaler_Strompreis,\n        AVG(sp.Bruttopreis) AS Durchschnittspreis,\n        SUM(sv.Netzverbrauch_pro_stunde * sp.Bruttopreis) / SUM(sv.Netzverbrauch_pro_stunde) AS Mein_Durchschnittspreis_Verbrauch\n    FROM stundenweise_verbrauch sv\n    JOIN Strompreise sp ON sv.Stunde = strftime('%Y-%m-%d %H:00:00', sp.Zeitpunkt)\n    GROUP BY strftime('%Y-%m-%d', sv.Stunde)\n),\nmonatsweise_kosten AS (\n    SELECT\n        strftime('%m-%Y', tk.Tag) AS Monat,\n        strftime('%Y', tk.Tag) AS Jahr,\n        strftime('%m', tk.Tag) AS Monat_nummer,\n        SUM(tk.Tagesverbrauch) AS Monatsverbrauch,\n        SUM(tk.Tagesstromkosten) AS Monatsstromkosten,\n        MIN(tk.Minimaler_Strompreis) AS Minimaler_Strompreis,\n        MAX(tk.Maximaler_Strompreis) AS Maximaler_Strompreis,\n        AVG(tk.Durchschnittspreis) AS Durchschnittspreis,\n        SUM(tk.Tagesstromkosten) / SUM(tk.Tagesverbrauch) AS Mein_Durchschnittspreis_Verbrauch\n    FROM tagesweise_kosten tk\n    GROUP BY strftime('%m-%Y', tk.Tag)\n)\nSELECT\n    Monat,\n    Monatsverbrauch,\n    ROUND(Monatsstromkosten / 1000.0, 2) AS Monatsstromkosten,\n    Mein_Durchschnittspreis_Verbrauch,\n    Durchschnittspreis,\n    Minimaler_Strompreis,\n    Maximaler_Strompreis\nFROM monatsweise_kosten\nORDER BY \n    Jahr DESC,        -- Jüngstes Jahr zuerst (absteigend)\n    Monat_nummer DESC; -- Innerhalb des Jahres: Dezember (12) zuerst (absteigend)",
     "rawQueryText": "WITH verbrauchview AS (\n    SELECT\n        Zeitpunkt,\n        LEAD(Netzverbrauch) OVER (ORDER BY Zeitpunkt) - Netzverbrauch AS Netzverbrauch_pro_stunde,\n        LEAD(AC_TO_DC) OVER (ORDER BY Zeitpunkt) - AC_TO_DC AS AC_TO_DC_pro_stunde,\n        LEAD(AC_Produktion) OVER (ORDER BY Zeitpunkt) - AC_Produktion AS AC_Produktion_pro_stunde,\n        LEAD(DC_Produktion) OVER (ORDER BY Zeitpunkt) - DC_Produktion AS DC_Produktion_pro_stunde,\n        LEAD(Einspeisung) OVER (ORDER BY Zeitpunkt) - Einspeisung AS Einspeisung_pro_stunde,\n        LEAD(Batterie_IN) OVER (ORDER BY Zeitpunkt) - Batterie_IN AS Batterie_IN_pro_stunde,\n        LEAD(Batterie_OUT) OVER (ORDER BY Zeitpunkt) - Batterie_OUT AS Batterie_OUT_pro_stunde\n    FROM pv_daten\n    WHERE\n        Zeitpunkt >= datetime($__from / 1000 - 3600, 'unixepoch') AND\n        Zeitpunkt <= datetime($__to / 1000 + 3600, 'unixepoch')\n),\nstundenweise_verbrauch AS (\n    SELECT\n        strftime('%Y-%m-%d %H:00:00', Zeitpunkt) AS Stunde,\n        SUM(Netzverbrauch_pro_stunde) AS Netzverbrauch_pro_stunde,\n        SUM(AC_TO_DC_pro_stunde) AS AC_TO_DC_pro_stunde\n    FROM verbrauchview\n    WHERE\n        Zeitpunkt >= datetime($__from / 1000 , 'unixepoch') AND\n        Zeitpunkt <= datetime($__to / 1000 , 'unixepoch')\n    GROUP BY strftime('%Y-%m-%d %H:00:00', Zeitpunkt)\n),\ntagesweise_kosten AS (\n    SELECT\n        strftime('%Y-%m-%d', sv.Stunde) AS Tag,\n        SUM(sv.Netzverbrauch_pro_stunde) AS Tagesverbrauch,\n        SUM(sv.Netzverbrauch_pro_stunde * sp.Bruttopreis) AS Tagesstromkosten,\n        MIN(sp.Bruttopreis) AS Minimaler_Strompreis,\n        MAX(sp.Bruttopreis) AS Maximaler_Strompreis,\n        AVG(sp.Bruttopreis) AS Durchschnittspreis,\n        SUM(sv.Netzverbrauch_pro_stunde * sp.Bruttopreis) / SUM(sv.Netzverbrauch_pro_stunde) AS Mein_Durchschnittspreis_Verbrauch\n    FROM stundenweise_verbrauch sv\n    JOIN Strompreise sp ON sv.Stunde = strftime('%Y-%m-%d %H:00:00', sp.Zeitpunkt)\n    GROUP BY strftime('%Y-%m-%d', sv.Stunde)\n),\nmonatsweise_kosten AS (\n    SELECT\n        strftime('%m-%Y', tk.Tag) AS Monat,\n        strftime('%Y', tk.Tag) AS Jahr,\n        strftime('%m', tk.Tag) AS Monat_nummer,\n        SUM(tk.Tagesverbrauch) AS Monatsverbrauch,\n        SUM(tk.Tagesstromkosten) AS Monatsstromkosten,\n        MIN(tk.Minimaler_Strompreis) AS Minimaler_Strompreis,\n        MAX(tk.Maximaler_Strompreis) AS Maximaler_Strompreis,\n        AVG(tk.Durchschnittspreis) AS Durchschnittspreis,\n        SUM(tk.Tagesstromkosten) / SUM(tk.Tagesverbrauch) AS Mein_Durchschnittspreis_Verbrauch\n    FROM tagesweise_kosten tk\n    GROUP BY strftime('%m-%Y', tk.Tag)\n)\nSELECT\n    Monat,\n    Monatsverbrauch,\n    ROUND(Monatsstromkosten / 1000.0, 2) AS Monatsstromkosten,\n    Mein_Durchschnittspreis_Verbrauch,\n    Durchschnittspreis,\n    Minimaler_Strompreis,\n    Maximaler_Strompreis\nFROM monatsweise_kosten\nORDER BY \n    Jahr DESC,        -- Jüngstes Jahr zuerst (absteigend)\n    Monat_nummer DESC; -- Innerhalb des Jahres: Dezember (12) zuerst (absteigend)",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  }
 ]
}