{
 "title": "SQLITEAuswertung View Tagesübersicht",
 "time": { "from": "now-1d/d", "to": "now-1d/d" },
 "panels": [
  {
   "title": "Strompreise",
   "type": "barchart",
   "gridPos": { "h": 14, "w": 21, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "targets": [
    {
     "queryText": "SELECT\n  strftime('%H:00', Zeitpunkt) AS Zeitpunkt,\n  Bruttopreis\nFROM strompreise\nWHERE\n  Zeitpunkt >= datetime($__from / 1000+ 3600, 'unixepoch') AND\n  Zeitpunkt <= datetime($__to / 1000  + 3600, 'unixepoch')\nGROUP BY strftime('%H:00', Zeitpunkt)\nORDER BY Zeitpunkt;",
     "rawQueryText": "SELECT\n  strftime('%H:00', Zeitpunkt) AS Zeitpunkt,\n  Bruttopreis\nFROM strompreise\nWHERE\n  Zeitpunkt >= datetime($__from / 1000+ 3600, 'unixepoch') AND\n  Zeitpunkt <= datetime($__to / 1000  + 3600, 'unixepoch')\nGROUP BY strftime('%H:00', Zeitpunkt)\nORDER BY Zeitpunkt;",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Netzverbrauch",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 21, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "targets": [
    {
     "queryText": "\nWITH verbrauch AS (\nSELECT\n  Zeitpunkt,\n  LEAD(Netzverbrauch) OVER (ORDER BY Zeitpunkt) - Netzverbrauch AS \"Netzverbrauch\"\nFROM pv_daten\nWHERE\n  Zeitpunkt >= datetime($__from / 1000+ 3600, 'unixepoch') AND\n  Zeitpunkt <= datetime($__to / 1000  + 3600, 'unixepoch')\n) \nSELECT\n  strftime('%H:00', Zeitpunkt) AS \"Zeitpunkt\",\n  sum(Netzverbrauch) AS \"Netzverbrauch\"\nFROM verbrauch\nGROUP BY strftime('%H:00', Zeitpunkt)\nORDER BY Zeitpunkt;\n\n\n",
     "rawQueryText": "\nWITH verbrauch AS (\nSELECT\n  Zeitpunkt,\n  LEAD(Netzverbrauch) OVER (ORDER BY Zeitpunkt) - Netzverbrauch AS \"Netzverbrauch\"\nFROM pv_daten\nWHERE\n  Zeitpunkt >= datetime($__from / 1000+ 3600, 'unixepoch') AND\n  Zeitpunkt <= datetime($__to / 1000  + 3600, 'unixepoch')\n) \nSELECT\n  strftime('%H:00', Zeitpunkt) AS \"Zeitpunkt\",\n  sum(Netzverbrauch) AS \"Netzverbrauch\"\nFROM verbrauch\nGROUP BY strftime('%H:00', Zeitpunkt)\nORDER BY Zeitpunkt;\n\n\n",
     "source": "url",
     "timeColumns": [
      "time",
      "ts"
     ],
     "type": "json",
     "url": "https://github.com/grafana/grafana-infinity-datasource/blob/main/testdata/users.json",
     "url_options": { "data": "", "method": "GET" }
    }
   ]
  },
  {
   "title": "AC Produktion",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 21, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "targets": [
    {
     "queryText": "WITH verbrauchview AS (\nSELECT\n  Zeitpunkt,\n  LEAD(AC_Produktion) OVER (ORDER BY Zeitpunkt) - AC_Produktion AS \"AC_Produktion\"\n \nFROM pv_daten\nWHERE\n  Zeitpunkt >= datetime($__from / 1000 + 3600, 'unixepoch') AND\n  Zeitpunkt <= datetime($__to / 1000 + 3600, 'unixepoch')\n)\nSELECT\n  strftime('%H:00 ', Zeitpunkt) AS \"Zeitpunkt\",\n  sum(AC_Produktion) AS \"AC Produktion\"\nFROM verbrauchview\nGROUP BY strftime('%H:00', Zeitpunkt)\nORDER BY Zeitpunkt;\n",
     "rawQueryText": "WITH verbrauchview AS (\nSELECT\n  Zeitpunkt,\n  LEAD(AC_Produktion) OVER (ORDER BY Zeitpunkt) - AC_Produktion AS \"AC_Produktion\"\n \nFROM pv_daten\nWHERE\n  Zeitpunkt >= datetime($__from / 1000 + 3600, 'unixepoch') AND\n  Zeitpunkt <= datetime($__to / 1000 + 3600, 'unixepoch')\n)\nSELECT\n  strftime('%H:00 ', Zeitpunkt) AS \"Zeitpunkt\",\n  sum(AC_Produktion) AS \"AC Produktion\"\nFROM verbrauchview\nGROUP BY strftime('%H:00', Zeitpunkt)\nORDER BY Zeitpunkt;\n",
     "source": "url",
     "timeColumns": [
      "time",
      "ts"
     ],
     "type": "json",
     "url": "https://github.com/grafana/grafana-infinity-datasource/blob/main/testdata/users.json",
     "url_options": { "data": "", "method": "GET" }
    }
   ]
  },
  {
   "title": "BattNetzladung",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 21, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "targets": [
    {
     "queryText": "WITH verbrauchview AS (\nSELECT\n  Zeitpunkt,\n  LEAD(AC_to_DC) OVER (ORDER BY Zeitpunkt) - AC_to_DC AS \"AC_to_DC\"\nFROM pv_daten\nWHERE\n  Zeitpunkt >= datetime($__from / 1000 + 3600, 'unixepoch') AND\n  Zeitpunkt <= datetime($__to / 1000 + 3600, 'unixepoch')\n) \nSELECT\n  strftime('%H:00 ', Zeitpunkt) AS \"Zeitpunkt\",\n  sum(AC_to_DC) AS \"BattNetzladung\"\nFROM verbrauchview\nGROUP BY strftime('%H:00', Zeitpunkt)\nORDER BY Zeitpunkt;\n",
     "rawQueryText": "WITH verbrauchview AS (\nSELECT\n  Zeitpunkt,\n  LEAD(AC_to_DC) OVER (ORDER BY Zeitpunkt) - AC_to_DC AS \"AC_to_DC\"\nFROM pv_daten\nWHERE\n  Zeitpunkt >= datetime($__from / 1000 + 3600, 'unixepoch') AND\n  Zeitpunkt <= datetime($__to / 1000 + 3600, 'unixepoch')\n) \nSELECT\n  strftime('%H:00 ', Zeitpunkt) AS \"Zeitpunkt\",\n  sum(AC_to_DC) AS \"BattNetzladung\"\nFROM verbrauchview\nGROUP BY strftime('%H:00', Zeitpunkt)\nORDER BY Zeitpunkt;\n",
     "source": "url",
     "timeColumns": [
      "time",
      "ts"
     ],
     "type": "json",
     "url": "https://github.com/grafana/grafana-infinity-datasource/blob/main/testdata/users.json",
     "url_options": { "data": "", "method": "GET" }
    }
   ]
  },
  {
   "title": "Vorhersage",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 21, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "targets": [
    {
     "queryText": "SELECT\n  strftime('%H:00', Zeitpunkt) AS \"Zeitpunkt\",\n Vorhersage AS \"Vorhersage\"\nFROM PV_Daten\nWHERE\n  Zeitpunkt >= datetime(1741042800000 / 1000 + 3600, 'unixepoch') AND\n  Zeitpunkt <= datetime(1741129199999 / 1000 + 3600, 'unixepoch')\nGROUP BY strftime('%Y-%m-%d %H:00:00', Zeitpunkt)\nORDER BY Zeitpunkt;\n\n",
     "rawQueryText": "SELECT\n  strftime('%H:00', Zeitpunkt) AS \"Zeitpunkt\",\n Vorhersage AS \"Vorhersage\"\nFROM PV_Daten\nWHERE\n  Zeitpunkt >= datetime($__from / 1000 + 3600, 'unixepoch') AND\n  Zeitpunkt <= datetime($__to / 1000 + 3600, 'unixepoch')\nGROUP BY strftime('%Y-%m-%d %H:00:00', Zeitpunkt)\nORDER BY Zeitpunkt;\n\n",
     "source": "url",
     "timeColumns": [
      "time",
      "ts"
     ],
     "type": "json",
     "url": "https://github.com/grafana/grafana-infinity-datasource/blob/main/testdata/users.json",
     "url_options": { "data": "", "method": "GET" }
    }
   ]
  },
  {
   "title": "SOC Batterie",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 21, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "queryText": "SELECT\n Zeitpunkt,\n BattStatus AS \"Batterie SOC\"\nFROM PV_Daten\nWHERE\n  Zeitpunkt >= datetime($__from / 1000+3600, 'unixepoch') AND\n  Zeitpunkt <= datetime($__to / 1000+3600, 'unixepoch')\nORDER BY Zeitpunkt;\n",
     "rawQueryText": "SELECT\n Zeitpunkt,\n BattStatus AS \"Batterie SOC\"\nFROM PV_Daten\nWHERE\n  Zeitpunkt >= datetime($__from / 1000+3600, 'unixepoch') AND\n  Zeitpunkt <= datetime($__to / 1000+3600, 'unixepoch')\nORDER BY Zeitpunkt;\n",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "DC Produktion",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 21, "x": 0, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "targets": [
    {
     "queryText": "WITH verbrauchview AS (\nSELECT\n  Zeitpunkt,\n  LEAD(DC_Produktion) OVER (ORDER BY Zeitpunkt) - DC_Produktion AS \"DC_Produktion\"\nFROM pv_daten\nWHERE\n  Zeitpunkt >= datetime($__from / 1000 + 3600, 'unixepoch') AND\n  Zeitpunkt <= datetime($__to / 1000 + 3600, 'unixepoch')\n)\nSELECT\n  strftime('%H:00', Zeitpunkt) AS \"Zeitpunkt\",\n  sum(DC_Produktion) AS \"DC Produktion\"\nFROM verbrauchview\nGROUP BY strftime('%H:00', Zeitpunkt)\nORDER BY Zeitpunkt;\n",
     "rawQueryText": "WITH verbrauchview AS (\nSELECT\n  Zeitpunkt,\n  LEAD(DC_Produktion) OVER (ORDER BY Zeitpunkt) - DC_Produktion AS \"DC_Produktion\"\nFROM pv_daten\nWHERE\n  Zeitpunkt >= datetime($__from / 1000 + 3600, 'unixepoch') AND\n  Zeitpunkt <= datetime($__to / 1000 + 3600, 'unixepoch')\n)\nSELECT\n  strftime('%H:00', Zeitpunkt) AS \"Zeitpunkt\",\n  sum(DC_Produktion) AS \"DC Produktion\"\nFROM verbrauchview\nGROUP BY strftime('%H:00', Zeitpunkt)\nORDER BY Zeitpunkt;\n",
     "source": "url",
     "timeColumns": [
      "time",
      "ts"
     ],
     "type": "json",
     "url": "https://github.com/grafana/grafana-infinity-datasource/blob/main/testdata/users.json",
     "url_options": { "data": "", "method": "GET" }
    }
   ]
  },
  {
   "title": "Einspeisung",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 21, "x": 0, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "targets": [
    {
     "queryText": "WITH verbrauchview AS (\nSELECT\n  Zeitpunkt,\n  LEAD(Einspeisung) OVER (ORDER BY Zeitpunkt) - Einspeisung AS \"Einspeisung\"\n  \nFROM pv_daten\nWHERE\n  Zeitpunkt >= datetime($__from / 1000 + 3600, 'unixepoch') AND\n  Zeitpunkt <= datetime($__to / 1000 + 3600, 'unixepoch')\n) \nSELECT\n  strftime('%H:00', Zeitpunkt) AS \"Zeitpunkt\",\n  sum(Einspeisung) AS \"Einspeisung\"\nFROM verbrauchview\nGROUP BY strftime('%H:00', Zeitpunkt)\nORDER BY Zeitpunkt;\n\n\n",
     "rawQueryText": "WITH verbrauchview AS (\nSELECT\n  Zeitpunkt,\n  LEAD(Einspeisung) OVER (ORDER BY Zeitpunkt) - Einspeisung AS \"Einspeisung\"\n  \nFROM pv_daten\nWHERE\n  Zeitpunkt >= datetime($__from / 1000 + 3600, 'unixepoch') AND\n  Zeitpunkt <= datetime($__to / 1000 + 3600, 'unixepoch')\n) \nSELECT\n  strftime('%H:00', Zeitpunkt) AS \"Zeitpunkt\",\n  sum(Einspeisung) AS \"Einspeisung\"\nFROM verbrauchview\nGROUP BY strftime('%H:00', Zeitpunkt)\nORDER BY Zeitpunkt;\n\n\n",
     "source": "url",
     "timeColumns": [
      "time",
      "ts"
     ],
     "type": "json",
     "url": "https://github.com/grafana/grafana-infinity-datasource/blob/main/testdata/users.json",
     "url_options": { "data": "", "method": "GET" }
    }
   ]
  },
  {
   "title": "In Batterie geladen",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 21, "x": 0, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "targets": [
    {
     "queryText": "WITH verbrauchview AS (\nSELECT\n  Zeitpunkt,\n  LEAD(Batterie_IN) OVER (ORDER BY Zeitpunkt) - Batterie_IN AS \"Batterie_IN\"\nFROM pv_daten\nWHERE\n  Zeitpunkt >= datetime($__from / 1000 + 3600, 'unixepoch') AND\n  Zeitpunkt <= datetime($__to / 1000 + 3600, 'unixepoch')\n)\nSELECT\n  strftime('%H:00', Zeitpunkt) AS \"Zeitpunkt\",\n  sum(Batterie_In) AS \"In Batterie\"\nFROM verbrauchview\nGROUP BY strftime('%H:00', Zeitpunkt)\nORDER BY Zeitpunkt;\n\n\n",
     "rawQueryText": "WITH verbrauchview AS (\nSELECT\n  Zeitpunkt,\n  LEAD(Batterie_IN) OVER (ORDER BY Zeitpunkt) - Batterie_IN AS \"Batterie_IN\"\nFROM pv_daten\nWHERE\n  Zeitpunkt >= datetime($__from / 1000 + 3600, 'unixepoch') AND\n  Zeitpunkt <= datetime($__to / 1000 + 3600, 'unixepoch')\n)\nSELECT\n  strftime('%H:00', Zeitpunkt) AS \"Zeitpunkt\",\n  sum(Batterie_In) AS \"In Batterie\"\nFROM verbrauchview\nGROUP BY strftime('%H:00', Zeitpunkt)\nORDER BY Zeitpunkt;\n\n\n",
     "source": "url",
     "timeColumns": [
      "time",
      "ts"
     ],
     "type": "json",
     "url": "https://github.com/grafana/grafana-infinity-datasource/blob/main/testdata/users.json",
     "url_options": { "data": "", "method": "GET" }
    }
   ]
  },
  {
   "title": "Aus Batterie geladen",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 21, "x": 0, "y": 71 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "targets": [
    {
     "queryText": "WITH verbrauchview AS (\nSELECT\n  Zeitpunkt,\n  LEAD(Batterie_OUT) OVER (ORDER BY Zeitpunkt) - Batterie_OUT AS \"Batterie_OUT\"\nFROM pv_daten\nWHERE\n  Zeitpunkt >= datetime(1741042800000 / 1000 + 3600, 'unixepoch') AND\n  Zeitpunkt <= datetime(1741129199999 / 1000 + 3600, 'unixepoch')\n) \nSELECT\n  strftime('%H:00', Zeitpunkt) AS \"Zeitpunkt\",\n  sum(Batterie_Out) AS \"Aus Batterie\"\nFROM verbrauchview\nGROUP BY strftime('%H:00', Zeitpunkt)\nORDER BY Zeitpunkt;\n\n\n",
     "rawQueryText": "WITH verbrauchview AS (\nSELECT\n  Zeitpunkt,\n  LEAD(Batterie_OUT) OVER (ORDER BY Zeitpunkt) - Batterie_OUT AS \"Batterie_OUT\"\nFROM pv_daten\nWHERE\n  Zeitpunkt >= datetime($__from / 1000 + 3600, 'unixepoch') AND\n  Zeitpunkt <= datetime($__to / 1000 + 3600, 'unixepoch')\n) \nSELECT\n  strftime('%H:00', Zeitpunkt) AS \"Zeitpunkt\",\n  sum(Batterie_Out) AS \"Aus Batterie\"\nFROM verbrauchview\nGROUP BY strftime('%H:00', Zeitpunkt)\nORDER BY Zeitpunkt;\n\n\n",
     "source": "url",
     "timeColumns": [
      "time",
      "ts"
     ],
     "type": "json",
     "url": "https://github.com/grafana/grafana-infinity-datasource/blob/main/testdata/users.json",
     "url_options": { "data": "", "method": "GET" }
    }
   ]
  }
 ]
}