{
 "title": "Strompreise",
 "time": { "from": "now/d", "to": "now/d" },
 "panels": [
  {
   "title": "1 Tag vorher",
   "type": "barchart",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "queryText": "WITH timemove AS (\nSELECT\n  Zeitpunkt,\n  Bruttopreis AS \"Bruttopreis\"\nFROM strompreise\nWHERE\n  Zeitpunkt >= datetime($__from / 1000 -  90000, 'unixepoch') AND\n  Zeitpunkt <= datetime($__to / 1000  + 82800, 'unixepoch')\n)\n\n\nSELECT\n  strftime('%H:00', Zeitpunkt) AS \"Zeitpunkt\",\n  Bruttopreis AS \"Bruttopreis\"\nFROM timemove\nWHERE\n  Zeitpunkt >= datetime($__from / 1000 - 86400, 'unixepoch') AND\n  Zeitpunkt <= datetime($__to / 1000 - 86400, 'unixepoch')\nGROUP BY strftime('%H:00', Zeitpunkt)\nORDER BY Zeitpunkt;",
     "rawQueryText": "WITH timemove AS (\nSELECT\n  Zeitpunkt,\n  Bruttopreis AS \"Bruttopreis\"\nFROM strompreise\nWHERE\n  Zeitpunkt >= datetime($__from / 1000 -  90000, 'unixepoch') AND\n  Zeitpunkt <= datetime($__to / 1000  + 82800, 'unixepoch')\n)\n\n\nSELECT\n  strftime('%H:00', Zeitpunkt) AS \"Zeitpunkt\",\n  Bruttopreis AS \"Bruttopreis\"\nFROM timemove\nWHERE\n  Zeitpunkt >= datetime($__from / 1000 - 86400, 'unixepoch') AND\n  Zeitpunkt <= datetime($__to / 1000 - 86400, 'unixepoch')\nGROUP BY strftime('%H:00', Zeitpunkt)\nORDER BY Zeitpunkt;",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "$__from -> $__to     ---< Datum ausgewählt über Time-Picker >---",
   "type": "barchart",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 11 },
   "targets": [
    {
     "queryText": "WITH timemove AS (\nSELECT\n  Zeitpunkt,\n  Bruttopreis AS \"Bruttopreis\"\nFROM strompreise\nWHERE\n  Zeitpunkt >= datetime($__from / 1000 -  3600, 'unixepoch') AND\n  Zeitpunkt <= datetime($__to / 1000  + 3600, 'unixepoch')\n)\n\n\nSELECT\n  strftime('%H:00', Zeitpunkt) AS \"Zeitpunkt\",\n  Bruttopreis AS \"Bruttopreis\"\nFROM timemove\nWHERE\n  Zeitpunkt >= datetime($__from / 1000, 'unixepoch') AND\n  Zeitpunkt <= datetime($__to / 1000, 'unixepoch')\nGROUP BY strftime('%H:00', Zeitpunkt)\nORDER BY Zeitpunkt;",
     "rawQueryText": "WITH timemove AS (\nSELECT\n  Zeitpunkt,\n  Bruttopreis AS \"Bruttopreis\"\nFROM strompreise\nWHERE\n  Zeitpunkt >= datetime($__from / 1000 -  3600, 'unixepoch') AND\n  Zeitpunkt <= datetime($__to / 1000  + 3600, 'unixepoch')\n)\n\n\nSELECT\n  strftime('%H:00', Zeitpunkt) AS \"Zeitpunkt\",\n  Bruttopreis AS \"Bruttopreis\"\nFROM timemove\nWHERE\n  Zeitpunkt >= datetime($__from / 1000, 'unixepoch') AND\n  Zeitpunkt <= datetime($__to / 1000, 'unixepoch')\nGROUP BY strftime('%H:00', Zeitpunkt)\nORDER BY Zeitpunkt;",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "1 Tag später ",
   "type": "barchart",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 22 },
   "targets": [
    {
     "queryText": "WITH timemove AS (\nSELECT\n  Zeitpunkt,\n  Bruttopreis AS \"Bruttopreis\"\nFROM strompreise\nWHERE\n  Zeitpunkt >= datetime($__from / 1000 +  82800, 'unixepoch') AND\n  Zeitpunkt <= datetime($__to / 1000  + 93600, 'unixepoch')\n)\n\n\nSELECT\n  strftime('%H:00', Zeitpunkt) AS \"Zeitpunkt\",\n  Bruttopreis AS \"Bruttopreis\"\nFROM timemove\nWHERE\n  Zeitpunkt >= datetime($__from / 1000 + 86400, 'unixepoch') AND\n  Zeitpunkt <= datetime($__to / 1000 + 86400, 'unixepoch')\nGROUP BY strftime('%d %H:00', Zeitpunkt)\nORDER BY Zeitpunkt;",
     "rawQueryText": "WITH timemove AS (\nSELECT\n  Zeitpunkt,\n  Bruttopreis AS \"Bruttopreis\"\nFROM strompreise\nWHERE\n  Zeitpunkt >= datetime($__from / 1000 +  82800, 'unixepoch') AND\n  Zeitpunkt <= datetime($__to / 1000  + 93600, 'unixepoch')\n)\n\n\nSELECT\n  strftime('%H:00', Zeitpunkt) AS \"Zeitpunkt\",\n  Bruttopreis AS \"Bruttopreis\"\nFROM timemove\nWHERE\n  Zeitpunkt >= datetime($__from / 1000 + 86400, 'unixepoch') AND\n  Zeitpunkt <= datetime($__to / 1000 + 86400, 'unixepoch')\nGROUP BY strftime('%d %H:00', Zeitpunkt)\nORDER BY Zeitpunkt;",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  }
 ]
}